### ISSUE TITLE
react-native 0.51

### ISSUE THREAD

**Issue by eastFang** [kristerkari/react-native-less-transformer#2]
react-native@0.51 can't build,

**Comment by kristerkari** [comment]
thanks @eastFang !

What is the exact error that you are getting?

**Comment by eastFang** [comment]
react-native@0.55.4 work;
There are other problems；.less file can't  @import other less file
![image](https://user-images.githubusercontent.com/26185059/45278275-faf73d00-b4fe-11e8-95f0-f09149c4a91d.png)
![image](https://user-images.githubusercontent.com/26185059/45278290-0b0f1c80-b4ff-11e8-9be7-103dc0f35dcc.png)

**Comment by kristerkari** [comment]
@eastFang I released a new version (1.1.3) with a bug fix to make `@import` working. Please try it out and let me know if it fixes your problem.

**Comment by eastFang** [comment]
@kristerkari it works when import relative path. Thanks a lot!
