### ISSUE TITLE
Call renderToCSS without arguments

### ISSUE THREAD

**Issue by Darmody** [kristerkari/react-native-less-transformer#4]
![屏幕快照 2019-03-12 上午11 58 19](https://user-images.githubusercontent.com/6788752/54173761-2b279480-44be-11e9-8769-4b519161ecd7.png)

Can't run the transformer until I add arguments to renderToCSS. BUG I think?

**Comment by kristerkari** [comment]
Yeah, I broke it accidentally. I'll make a fix :)

**Comment by kristerkari** [comment]
Version 1.2.1 has a fix for this. Thanks for reporting!

**Comment by Darmody** [comment]
@kristerkari  cooooooool
