### ISSUE TITLE
Not working on RN 0.59

### ISSUE THREAD

**Issue by MakarovAleksey** [kristerkari/react-native-less-transformer#5]
After updating the project to 0.59, I get the error:
`error: bundling failed: TypeError: Cannot destructure property `src` of 'undefined' or 'null'.
    at renderToCSS (node_modules/react-native-less-transformer/index.js:32:21)`

On version 0.58 everything is ok

UPD:
You can fix it by change this line
`return renderToCSS().then(css => {`
to
`return renderToCSS({ src, filename, options }).then(css => {`

**Comment by kristerkari** [comment]
Yeah, I broke it accidentally. I'll make a fix :)

**Comment by kristerkari** [comment]
Version 1.2.1 has a fix for this. Thanks for reporting!
