### ISSUE TITLE
semver issue

### ISSUE THREAD

**Issue by superyarik** [kristerkari/react-native-less-transformer#52]
using in expo and facing error while starting server
`Failed to construct transformer:  TypeError: semver is not a function`

console.log says that semver is object. so looks like we need change line
`var reactNativeMinorVersion = semver(reactNativeVersionString).minor;`
to
`var reactNativeMinorVersion = semver.minor(reactNativeVersionString);`

i have "react-native-less-transformer": "^1.4.0", 
inside have dependency semver v7.5.1.

**Comment by superyarik** [comment]
looks like vue transformer fix it
https://github.com/GeekyAnts/vue-native-cli/pull/48/files

**Comment by kristerkari** [comment]
yeah sorry, I forgot to update the code when updating to a newer semver version. I'll make a fix.

**Comment by kristerkari** [comment]
Fixed in 1.4.1

**Comment by Emiya0306** [comment]
@kristerkari Are you really fixed that? 😿 

<img width="735" alt="image" src="https://github.com/kristerkari/react-native-less-transformer/assets/12878132/446e456e-04a1-4e04-9a04-19ae133ae4aa">

<img width="791" alt="image" src="https://github.com/kristerkari/react-native-less-transformer/assets/12878132/16083ac3-c62e-4838-94c1-c088aab4cb54">
Pic 1 react-native-less-transformer code on npmjs.org 1.5.1 now

<img width="1410" alt="image" src="https://github.com/kristerkari/react-native-less-transformer/assets/12878132/ba5f356a-88b3-4f51-8fe0-7bd705fd9fc2">
Pic 2 The right code need to fix.

**Comment by kristerkari** [comment]
@Emiya0306 It looks like I had messed up the code a bit, can you please try with version 1.5.2 and let me know if that fixes the error?
